## Упражнения по библиотеке Numpy

In [22]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [23]:
mas = np.random.randint(20, size=10)
print(mas)
mas = np.where((mas > 3) & (mas < 8), mas * -1, mas)
print(mas)


[19 11  7 18 14 19 13  4 14  6]
[19 11 -7 18 14 19 13 -4 14 -6]


**2.** Заменить максимальный элемент случайного массива на 0

In [24]:
bas = np.random.randint(1000, size=10)
print(bas)
max_bas = np.max(bas)
print(max_bas)
bas = np.where((bas == max_bas), 0, bas)
print(bas)

[963 242 102 287 421 343 798 254 955  95]
963
[  0 242 102 287 421 343 798 254 955  95]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [25]:
a = np.random.randint(0, 4, (5, 5))
b = np.random.randint(0, 5, (5, 5))
print(a, b, sep='\n')
print(np.dot(a, b))



[[0 2 2 2 0]
 [1 3 2 2 3]
 [1 2 0 1 1]
 [0 2 2 1 3]
 [0 0 0 3 3]]
[[3 0 1 3 1]
 [3 3 1 1 4]
 [3 3 2 0 3]
 [0 4 3 3 1]
 [2 1 4 3 4]]
[[12 20 12  8 16]
 [24 26 26 21 33]
 [11 11 10 11 14]
 [18 19 21 14 27]
 [ 6 15 21 18 15]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [26]:
a = np.random.randint(0, 10, (8, 3))
b = np.random.randint(0, 10, (2, 2))
print("A: \n{}\nB: \n{}\n".format(a, b), end='\nOUT:\n\n')
x_i = np.isin(a, b)
print(x_i, end='\n\n')
true_sum_x_i = np.sum(x_i, axis=1)
print(true_sum_x_i, end="\n\n")
print(a[np.where(true_sum_x_i > 0)] )


A: 
[[4 7 6]
 [3 7 6]
 [2 0 3]
 [6 6 1]
 [9 9 6]
 [8 7 6]
 [1 0 5]
 [7 1 5]]
B: 
[[6 7]
 [8 5]]

OUT:

[[False  True  True]
 [False  True  True]
 [False False False]
 [ True  True False]
 [False False  True]
 [ True  True  True]
 [False False  True]
 [ True False  True]]

[2 2 0 2 1 3 1 2]

[[4 7 6]
 [3 7 6]
 [6 6 1]
 [9 9 6]
 [8 7 6]
 [1 0 5]
 [7 1 5]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [27]:
m = np.random.randint(0, 2, (10, 3))
print(m, type(m), end="\n\n")

# first solution:
for i in range(len(m)):
    if len(set(m[i])) > 1:
        print(m[i])

print("\nSolution 2:")

# second solution:
for i in range(len(m)):
    if len(np.unique(m[i])) > 1:
        print(m[i])

[[1 0 1]
 [1 0 0]
 [1 1 1]
 [0 0 1]
 [1 0 1]
 [1 0 1]
 [1 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 0]] <class 'numpy.ndarray'>

[1 0 1]
[1 0 0]
[0 0 1]
[1 0 1]
[1 0 1]
[1 1 0]
[0 1 1]
[1 0 0]
[1 0 0]

Solution 2:
[1 0 1]
[1 0 0]
[0 0 1]
[1 0 1]
[1 0 1]
[1 1 0]
[0 1 1]
[1 0 0]
[1 0 0]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [28]:
m = np.random.randint(1, 3, (10, 2))
print(m, end="\n\n")

m = np.unique(m, axis=0)
print(m)

[[2 1]
 [2 1]
 [2 1]
 [2 2]
 [2 2]
 [1 1]
 [1 2]
 [1 2]
 [1 2]
 [1 1]]

[[1 1]
 [1 2]
 [2 1]
 [2 2]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [29]:
# Python solution:
x_p = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]

for i in range(len(x_p[0])):
    b = 1
    b *= x_p[i][i]
print(b)

# Numpy solution:
x_n = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])

print(np.prod(np.diagonal(x_n)[np.diagonal(x_n) != 0]))



3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [30]:
# Python solution:
x, y = [1, 2, 2, 4], [4, 2, 1, 2]
print(sorted(x) == sorted(y))

# Numpy solution:
x, y = np.array([1, 2, 2, 4]), np.array([1, 2, 2, 4])
print(np.array_equal(np.sort(x), np.sort(y)))

True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [31]:
# Python solution:
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
max_el = 0
for i in range(1, len(x)):
    if x[i - 1] == 0 and x[i] > max_el:
        max_el = x[i]
print(max_el)

# Numpy solution:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zeroes = x == 0
# print(zeroes[:-1]) # -> [False False  True False  True  True False False]
# print(x[1:][5]) # -> 5
# print(x[:-1][zeroes[:-1]]) # -> [0 0 0]
# print(x[1:][zeroes[:-1]]) # -> [3 0 5]
print(x[1:][zeroes[:-1]].max())


5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [32]:
# Numpy solution:
x = np.array([2, 2, 2, 3, 3, 3, 5])
print(np.unique(x, return_counts=True))

# Python solution:
def encode(l):
    nums_unique = list(set(l))
    counter_list = list()
    for l_i in nums_unique:
        counter_list.append(l.count(l_i))
    goal_tuple = nums_unique, counter_list
    return goal_tuple

x = [2, 2, 2, 3, 3, 3, 5]
print(encode(x))


(array([2, 3, 5]), array([3, 3, 1]))
([2, 3, 5], [3, 3, 1])


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [33]:
import math
from scipy.spatial.distance import cdist
import time

x = [1, 2, 3], [1, 21, 3], [4, 5, 6], [4, 4, 5]
y = [4, 5, 6], [13, 10, 13], [1, 2, 3], [5, 6, 9]

# Python
def method(x, y):
    result = []
    for i in range(len(x)):
        l = []
        for j in range(len(y)):
            dist = 0
            for k in range(len(x[0])):
                dist += (x[i][k] - y[j][k]) ** 2
            l.append(math.sqrt(dist))
        result.append(l)
    return result

start_time = time.time()
print(method(x, y))
print("Python %s sec" % (time.time() - start_time), end="\n\n")

# Scipy
x_2 = np.array([*x])
y_2 = np.array([*y])

start_time = time.time()
print(cdist(x_2, y_2))
print("Skipy %s sec" % (time.time() - start_time))


[[5.196152422706632, 17.549928774784245, 0.0, 8.246211251235321], [16.55294535724685, 19.1049731745428, 19.0, 16.64331697709324], [0.0, 12.449899597988733, 5.196152422706632, 3.3166247903554], [1.4142135623730951, 13.45362404707371, 4.123105625617661, 4.58257569495584]]
Python 0.000141143798828125 sec

[[ 5.19615242 17.54992877  0.          8.24621125]
 [16.55294536 19.10497317 19.         16.64331698]
 [ 0.         12.4498996   5.19615242  3.31662479]
 [ 1.41421356 13.45362405  4.12310563  4.58257569]]
Skipy 0.0004258155822753906 sec


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [34]:
import numpy as np


1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [35]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [36]:
average_calories = np.mean(calorie_stats)
print(average_calories)
print(average_calories - 60)

106.88311688311688
46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [37]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [38]:
median_calories = np.median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [39]:
print(np.percentile(calorie_stats,95)) # -> 140
print(np.percentile(calorie_stats,4)) # -> 70.0 -> V

print(np.percentile(calorie_stats,3)) # -> 55.599999999999994 -> X



140.0
70.0
55.599999999999994


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [40]:
more_calories = np.mean((calorie_stats > 60) * 100)
print(more_calories)

# OR
more = np.sum(calorie_stats > 60)
more_calories = more * 100 / calorie_stats.size
print(more_calories)

96.1038961038961
96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [41]:
calorie_std = np.std(calorie_stats)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [42]:
# Медиана калорий составляет 110, среднее значение равно 106,88,со стандартным отклонением 19,36.
# По количеству калорий CrunchieMunchies находится в 4-м процентиле по отношению к остальным хлопьям для завтрака.
# 96.1% других злаков содержат больше калорий в сравнении с CrunchieMunchies.
# Исходя из вышеизложенной информации компания MyCrunch производит более низкалорийные хлопья в сравнении с большинством аналогов других проиводителей, что делает продукт CrunchieMunchies компании MyCrunch более конкуренотноспособным и привлекательным к покупке за счет своей полезности.
